[pytest]
markers =
    positive: тест проверяет успешный сценарий (happy path)
    negative: тест проверяет невалидный сценарий или ожидаемую ошибку
    smoke: быстрый тест для проверки основной функциональности
    regression: тест из полного набора регрессии
    db: тест обращается напрямую к базе данных для проверки
    roles: тест проверяет права доступа по ролям
addopts = --strict-markers --reruns 2 --reruns-delay 2